server:
  port: 8080

spring:
  application:
    name: user-management-service
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    org.springframework: TRACE
    com.example.usermanagement: DEBUG
    org.hibernate.SQL: DEBUG 